"""empty message

Revision ID: 5b25e70c6e01
Revises: 
Create Date: 2024-04-08 17:29:50.529999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b25e70c6e01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.drop_column('employees', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('team', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'team_id')
    # ### end Alembic commands ###
